name: Generate and Commit DI1 Charts

on:
  # Run daily at 00:30 UTC
  schedule:
    - cron: '30 0 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  generate_charts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get full history
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib numpy
      
      - name: Generate DI1 Charts
        run: |
          # Run the chart generation script
          python simple_charts.py
          
          # Print directory contents for debugging
          echo "Contents of charts directory:"
          ls -la charts/
      
      - name: Commit and push changes
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Print git status before adding
          echo "Git status before adding changes:"
          git status
          
          # Add charts directory
          git add charts/
          
          # Print git status after adding
          echo "Git status after adding changes:"
          git status
          
          # Create commit
          git commit -m "Update DI1 charts - $(date +'%Y-%m-%d')"
          
          # Push changes
          git push
