name: Generate DI1 Charts Daily

on:
  # Run daily at 00:30 UTC (after the data scraping workflow)
  schedule:
    - cron: '30 0 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  generate_charts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get all history to ensure we have the latest data
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib numpy
      
      - name: Generate DI1 Charts
        run: |
          # Run the chart generation script
          python di1_charts.py
      
      - name: Commit and push changes
        run: |
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Stage changes
          git add charts/
          
          # Commit only if there are changes
          if git diff --staged --quiet; then
            echo "No changes to charts, skipping commit"
          else
            git commit -m "Update DI1 charts - $(date +'%Y-%m-%d')"
            
            # Push changes
            git push
          fi
